# Generated by Django 4.0.5 on 2022-06-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_getfuel_brand_getfuel_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetFuel',
            new_name='Fuel',
        ),
    ]
