# Generated by Django 4.0.5 on 2022-06-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_getfuel_fuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='brand',
            new_name='name',
        ),
    ]
