# Generated by Django 4.0.4 on 2022-06-18 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_fuel_latitude_alter_fuel_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Unknown', max_length=70)),
                ('location', models.CharField(max_length=70, null=True)),
                ('address', models.CharField(max_length=70, null=True)),
                ('phone', models.CharField(max_length=70, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Unknown', max_length=70)),
                ('date', models.DateField(default=datetime.date(2022, 6, 18))),
                ('price', models.FloatField()),
                ('address', models.CharField(max_length=70, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fuelplaces')),
            ],
        ),
        migrations.DeleteModel(
            name='Fuel',
        ),
    ]
