# Generated by Django 4.0.5 on 2022-06-20 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_date_alter_fuelprices_place_alter_fuelprices_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Unknown', max_length=70)),
                ('location', models.CharField(max_length=70, null=True)),
                ('address', models.CharField(max_length=70, null=True)),
                ('phone', models.CharField(max_length=70, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Unknown', max_length=70)),
                ('price', models.FloatField()),
                ('address', models.CharField(max_length=70, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='api.date')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='api.fuelplace')),
            ],
        ),
        migrations.RemoveField(
            model_name='fuelprices',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fuelprices',
            name='place',
        ),
        migrations.DeleteModel(
            name='FuelPlaces',
        ),
        migrations.DeleteModel(
            name='FuelPrices',
        ),
    ]
