# Generated by Django 4.0.5 on 2022-06-21 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fuelplace_fuelprice_remove_fuelprices_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelprice',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 21)),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
