# Generated by Django 4.0.4 on 2022-07-22 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_fuelprice_date_delete_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelprice',
            name='address',
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 22)),
        ),
    ]
