# Generated by Django 4.0.4 on 2022-07-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_fuelprice_address_alter_fuelprice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelprice',
            old_name='place',
            new_name='address',
        ),
    ]
