# Generated by Django 4.0.4 on 2022-07-29 01:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_place_fuelprice_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelprice',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.fuelplace'),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 29)),
        ),
    ]
