# Generated by Django 4.0.5 on 2022-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getfuel',
            old_name='name',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='getfuel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
