# Generated by Django 4.0.4 on 2022-06-17 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_brand_fuel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='name',
        ),
        migrations.AddField(
            model_name='fuel',
            name='address',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='brand',
            field=models.CharField(default='Unknown', max_length=70),
        ),
        migrations.AddField(
            model_name='fuel',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 17)),
        ),
        migrations.AddField(
            model_name='fuel',
            name='description',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='latitude',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='location',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='longitude',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='phone',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='title',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='trading_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='price',
            field=models.FloatField(),
        ),
    ]
