# Generated by Django 4.0.4 on 2022-06-18 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_fuel_name_fuel_address_fuel_brand_fuel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='trading_name',
        ),
        migrations.AlterField(
            model_name='fuel',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 18)),
        ),
    ]
