# Generated by Django 4.0.4 on 2022-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_fuel_description_remove_fuel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
